#
#  Copyright 2016 Google Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# EarlGreyExample
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

PROJECT_NAME = 'EarlGreyExample'
TARGETS = %w[EarlGreyExampleTests EarlGreyExampleSwiftTests]

use_frameworks!

target "EarlGreyExampleTests" do
  project 'EarlGreyExample'

  inherit! :search_paths
  pod 'EarlGrey'
end

target "EarlGreyExampleSwiftTests" do
  project 'EarlGreyExample'

  inherit! :search_paths
  pod 'EarlGrey'
end

post_install do |installer|
  # Always install the newest EarlGrey gem
  require 'rubygems/command_manager'
  Gem::CommandManager.instance[:install].install_gem('earlgrey', Gem::Requirement.default)
  require 'earlgrey'

  # For each test target, you need to call the EarlGrey script's edit method once.
  TARGETS.each do |test_target|
    var_args = {}
    if test_target.include? "Swift"
      var_args = {swift: true}
    end
    configure_for_earlgrey(installer, PROJECT_NAME, test_target, test_target + '.xcscheme', var_args)
  end
end

