#
#  Copyright 2016 Google Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# EarlGreyExample
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

PROJECT_NAME = 'EarlGreyExample'
TEST_TARGET = 'EarlGreyExampleTests'
TEST_TARGET_SWIFT = 'EarlGreyExampleSwiftTests'

use_frameworks!

target TEST_TARGET do
  project 'EarlGreyExample'

  inherit! :search_paths
  pod 'EarlGrey'
end

target TEST_TARGET_SWIFT do
  project 'EarlGreyExample'

  inherit! :search_paths
  pod 'EarlGrey'
end

post_install do |installer|
  # If the EarlGrey gem is not present in your system, then install it.
  begin
    require 'earlgrey'
  rescue LoadError
    require 'rubygems/command_manager'
    Gem::CommandManager.instance[:install].install_gem('earlgrey', Gem::Requirement.default)
    require 'earlgrey'
  end

  # For each test target, you need to call the EarlGrey script's edit method once.
  configure_for_earlgrey(installer, PROJECT_NAME, TEST_TARGET, TEST_TARGET + '.xcscheme')
  configure_for_earlgrey(installer, PROJECT_NAME, TEST_TARGET_SWIFT, TEST_TARGET_SWIFT + '.xcscheme', {swift: true})
end

