//
// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#import <EarlGrey/GREYActionBlock.h>

/**
 * An interface that exposes UI element actions.
 */

@interface GREYJavascriptExecution : NSObject

/**
 *
 *
 *  @param js Javascript to execute as a string.
 *  @param outResult Any result generated by the javascript execution.
 *  @return A GREYAction that will execute javascript in a WebView.
 */
+ (GREYActionBlock *)executeJavascript:(NSString *)js output:(out __strong NSString **)outResult;

@end
